# Generated by Django 5.1.2 on 2024-10-25 12:30

import django.db.models.deletion
import django.utils.timezone
import order.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=order.models.order_code, editable=False, max_length=15, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('PACKAGING', 'Packaging'), ('DISPATCH', 'Dispatch'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
